-- SIPRO comparte el proyecto Supabase con otra aplicación. Todos sus objetos
-- usan el prefijo sipro_ para evitar colisiones y cambios sobre datos ajenos.

create table public.sipro_usuarios (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique references auth.users(id) on delete cascade,
  nombre varchar(100) not null check (char_length(trim(nombre)) between 2 and 100),
  email varchar(254) not null unique,
  rol varchar(20) not null default 'consulta'
    check (rol in ('admin', 'encargado', 'inventario', 'consulta')),
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table public.sipro_categorias (
  id bigint generated by default as identity primary key,
  nombre varchar(80) not null unique,
  activo boolean not null default true,
  creado_en timestamptz not null default now()
);

create table public.sipro_productos (
  id bigint generated by default as identity primary key,
  codigodebarra varchar(100) not null unique,
  nombre varchar(150) not null,
  precio numeric(12,2) not null check (precio >= 0),
  categoria_id bigint not null references public.sipro_categorias(id),
  stock integer not null default 0 check (stock >= 0),
  stock_minimo integer not null default 10 check (stock_minimo >= 0),
  activo boolean not null default true,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table public.sipro_movimientos_stock (
  id bigint generated by default as identity primary key,
  producto_id bigint references public.sipro_productos(id) on delete set null,
  producto_nombre varchar(150) not null,
  tipo_movimiento varchar(10) not null
    check (tipo_movimiento in ('entrada', 'salida', 'ajuste')),
  cantidad integer not null check (cantidad > 0),
  usuario_id uuid references auth.users(id) on delete set null,
  nota varchar(300),
  fecha timestamptz not null default now()
);

create index sipro_productos_categoria_idx on public.sipro_productos(categoria_id);
create index sipro_productos_nombre_idx on public.sipro_productos(lower(nombre));
create index sipro_movimientos_producto_idx on public.sipro_movimientos_stock(producto_id);
create index sipro_movimientos_fecha_idx on public.sipro_movimientos_stock(fecha desc);

create or replace function public.sipro_role()
returns text language sql stable security invoker set search_path = ''
as $$
  select case
    when auth.jwt() -> 'app_metadata' ->> 'app' = 'sipro'
      then auth.jwt() -> 'app_metadata' ->> 'role'
    else null
  end
$$;

create or replace function public.sipro_handle_new_auth_user()
returns trigger language plpgsql security definer set search_path = ''
as $$
begin
  if new.raw_app_meta_data ->> 'app' = 'sipro' then
    insert into public.sipro_usuarios (auth_user_id, nombre, email, rol)
    values (
      new.id,
      coalesce(nullif(trim(new.raw_user_meta_data ->> 'name'), ''), split_part(new.email, '@', 1)),
      lower(new.email),
      coalesce(new.raw_app_meta_data ->> 'role', 'consulta')
    )
    on conflict (auth_user_id) do update set
      nombre = excluded.nombre, email = excluded.email, rol = excluded.rol,
      actualizado_en = now();
  end if;
  return new;
end;
$$;

drop trigger if exists sipro_on_auth_user_created on auth.users;
create trigger sipro_on_auth_user_created
  after insert or update of email, raw_user_meta_data, raw_app_meta_data on auth.users
  for each row execute function public.sipro_handle_new_auth_user();

create or replace function public.sipro_ajustar_stock(
  p_producto_id bigint, p_cantidad integer, p_tipo text, p_nota text default null
)
returns public.sipro_productos
language plpgsql security definer set search_path = ''
as $$
declare
  resultado public.sipro_productos;
begin
  if public.sipro_role() not in ('admin', 'encargado', 'inventario') then
    raise exception 'No autorizado' using errcode = '42501';
  end if;
  if p_cantidad is null or p_cantidad <= 0 or p_tipo not in ('entrada', 'salida') then
    raise exception 'Movimiento inválido' using errcode = '22023';
  end if;

  if p_tipo = 'salida' then
    update public.sipro_productos
       set stock = stock - p_cantidad, actualizado_en = now()
     where id = p_producto_id and activo and stock >= p_cantidad
     returning * into resultado;
  else
    update public.sipro_productos
       set stock = stock + p_cantidad, actualizado_en = now()
     where id = p_producto_id and activo
     returning * into resultado;
  end if;

  if not found then
    raise exception 'Stock insuficiente o producto inexistente' using errcode = 'P0001';
  end if;

  insert into public.sipro_movimientos_stock
    (producto_id, producto_nombre, tipo_movimiento, cantidad, usuario_id, nota)
  values
    (resultado.id, resultado.nombre, p_tipo, p_cantidad, auth.uid(), nullif(trim(p_nota), ''));
  return resultado;
end;
$$;

create or replace function public.sipro_crear_producto(
  p_codigodebarra text, p_nombre text, p_precio numeric,
  p_stock integer, p_categoria_id bigint, p_stock_minimo integer default 10
)
returns public.sipro_productos
language plpgsql security definer set search_path = ''
as $$
declare
  resultado public.sipro_productos;
begin
  if public.sipro_role() not in ('admin', 'encargado', 'inventario') then
    raise exception 'No autorizado' using errcode = '42501';
  end if;
  if nullif(trim(p_codigodebarra), '') is null or nullif(trim(p_nombre), '') is null
     or p_precio < 0 or p_stock < 0 or p_stock_minimo < 0 then
    raise exception 'Datos de producto inválidos' using errcode = '22023';
  end if;
  insert into public.sipro_productos
    (codigodebarra, nombre, precio, stock, stock_minimo, categoria_id)
  values
    (trim(p_codigodebarra), trim(p_nombre), p_precio, p_stock, p_stock_minimo, p_categoria_id)
  returning * into resultado;
  if p_stock > 0 then
    insert into public.sipro_movimientos_stock
      (producto_id, producto_nombre, tipo_movimiento, cantidad, usuario_id, nota)
    values
      (resultado.id, resultado.nombre, 'ajuste', p_stock, auth.uid(), 'Stock inicial');
  end if;
  return resultado;
end;
$$;

alter table public.sipro_usuarios enable row level security;
alter table public.sipro_categorias enable row level security;
alter table public.sipro_productos enable row level security;
alter table public.sipro_movimientos_stock enable row level security;

revoke all on table public.sipro_usuarios from anon, authenticated;
revoke all on table public.sipro_categorias from anon, authenticated;
revoke all on table public.sipro_productos from anon, authenticated;
revoke all on table public.sipro_movimientos_stock from anon, authenticated;
grant select on public.sipro_usuarios to authenticated;
grant select on public.sipro_categorias to authenticated;
grant select, delete on public.sipro_productos to authenticated;
grant update (codigodebarra, nombre, precio, categoria_id, stock_minimo, activo, actualizado_en)
  on public.sipro_productos to authenticated;
grant select on public.sipro_movimientos_stock to authenticated;
grant usage, select on sequence public.sipro_productos_id_seq to authenticated;
grant all on table public.sipro_usuarios, public.sipro_categorias, public.sipro_productos, public.sipro_movimientos_stock to service_role;
grant usage, select on all sequences in schema public to service_role;
revoke all on function public.sipro_ajustar_stock(bigint, integer, text, text) from public, anon;
grant execute on function public.sipro_ajustar_stock(bigint, integer, text, text) to authenticated;
grant execute on function public.sipro_ajustar_stock(bigint, integer, text, text) to service_role;
revoke all on function public.sipro_crear_producto(text, text, numeric, integer, bigint, integer) from public, anon;
grant execute on function public.sipro_crear_producto(text, text, numeric, integer, bigint, integer) to authenticated, service_role;

create policy sipro_usuarios_select on public.sipro_usuarios
for select to authenticated using (
  public.sipro_role() = 'admin' or (auth_user_id = auth.uid() and activo)
);
create policy sipro_categorias_select on public.sipro_categorias
for select to authenticated using (
  public.sipro_role() in ('admin', 'encargado', 'inventario', 'consulta')
);
create policy sipro_productos_select on public.sipro_productos
for select to authenticated using (
  public.sipro_role() in ('admin', 'encargado', 'inventario', 'consulta')
);
create policy sipro_productos_insert on public.sipro_productos
for insert to authenticated with check (
  public.sipro_role() in ('admin', 'encargado', 'inventario')
);
create policy sipro_productos_update on public.sipro_productos
for update to authenticated using (
  public.sipro_role() in ('admin', 'encargado', 'inventario')
) with check (
  public.sipro_role() in ('admin', 'encargado', 'inventario')
);
create policy sipro_productos_delete on public.sipro_productos
for delete to authenticated using (public.sipro_role() = 'admin');
create policy sipro_movimientos_select on public.sipro_movimientos_stock
for select to authenticated using (
  public.sipro_role() in ('admin', 'encargado', 'inventario', 'consulta')
);
