-- FASE 3: Historial de ejecución (fácil de cambiar de almacenamiento: es una tabla PostgREST estándar)
create table if not exists public.monitor_history (
  id bigint generated by default as identity primary key,
  service text not null,
  ok boolean not null,
  status text,
  latency_ms integer,
  details jsonb,
  checked_at timestamptz not null default now()
);

create index if not exists idx_monitor_history_service
  on public.monitor_history (service, checked_at desc);

-- FASE 4: último estado conocido por servicio (para alertas por transición: cayó / se recuperó)
create table if not exists public.monitor_state (
  service text primary key,
  last_ok boolean,
  last_status text,
  updated_at timestamptz not null default now()
);

alter table public.monitor_history enable row level security;
alter table public.monitor_state enable row level security;

-- El monitor (n8n) escribe/lee usando la anon key
create policy "anon insert history" on public.monitor_history
  for insert to anon with check (true);

create policy "anon select history" on public.monitor_history
  for select to anon using (true);

create policy "anon insert state" on public.monitor_state
  for insert to anon with check (true);

create policy "anon select state" on public.monitor_state
  for select to anon using (true);

create policy "anon update state" on public.monitor_state
  for update to anon using (true);
;
